### PR TITLE
Create Code_of_Conduct.md

### PR DESCRIPTION
**Pull request by jyothimanoj12**
** THIS FIXED THE ISSUE #31 **

ADDED A Code_of_Conduct.md

PLZ ADD gsoc-ext , level 1 , hacktoberfest-accepted tag

### CODE REVIEW

**Comment by satyam8932** [comment]
Can you please share me the screenshot of what you did?

**Comment by jyothimanoj12** [comment]
> Can you please share me the screenshot of what you did?

Screenshot 2024-10-08 012149
Screenshot 2024-10-08 012204
Screenshot 2024-10-08 012217
Screenshot 2024-10-08 012232

**Comment by satyam8932** [comment]
Thanks for your contributions @jyothimanoj12 
If you would like to fix more issues or create new features then you are welcome to do so.

**Comment by jyothimanoj12** [comment]
Hey @satyam8932 , my points for this contribution has not been awarded yet , can you check why , is the tags correctly labelled ?        Thank you

**Comment by jyothimanoj12** [comment]
> Hey @satyam8932 , my points for this contribution has not been awarded yet , can you check why , is the tags correctly labelled ?        Thank you 

Its added now

**Pull request merged**
