### PR TITLE
FAQ section addition

### PR DESCRIPTION
**Pull request by dev129**
Hi @satyam8932 

## What does this PR do?

This PR addresses issue #65 , which focuses on the design of the FAQ section located in `/components/ui/faq.tsx`. The changes made enhance the visual layout and responsiveness of the FAQ design, ensuring a better user experience across different devices.

### Motivation and Context
The motivation behind this change is to improve the usability and appearance of the FAQ section. This redesign aims to make the FAQs more accessible and visually appealing, allowing users to find information more efficiently.

### Dependencies
No new dependencies are required for this change.

### Visual Changes
For visual changes, please refer to the screenshots included in this PR:

- **Screenshots**
Desktop View:
image

Mobile View:
image

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

To verify the changes, the following tests should be conducted:

- [x ] Ensure that the FAQ section is responsive and displays correctly on various screen sizes.
- [x ] Validate that all FAQ items are accessible and readable.
- [ x] Check for any visual glitches or layout issues.

### Test Configuration
- Browser: Brave, Edge, Chrome

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent-sized PR without self-review might be rejected.

### CODE REVIEW

**Comment by satyam8932** [comment]
The Deployment got failed please look into the issues.

Thanks

**Comment by dev129** [comment]
I looked into it , and after seeing I got to know you have taken firebase into account and I defined the enviornement variables for it but its of no use :
image

All I was hoping was for adding faq component, but if its not able to be deployed better you unassign me.

**Comment by satyam8932** [comment]
image

The section is not responsive please look into the problem and try to fix it.

Thanks

**Comment by dev129** [comment]
@satyam8932 , it makes no sense , its not being deployed , correcting it is of no use , I have failed in it. It will waste our time , even if i correct then also its not deployable , so what's the use of it ?

**Comment by satyam8932** [comment]
Ok then no problem.
I will close this PR.

**Pull request closed without merging**
