### PR TITLE
Added dark/light mode feature

### PR DESCRIPTION
**Pull request by unknown91tech**
@satyam8932 I have added the dark/light mode feature for all the pages.

Can you review it and tell me if there are any changes to be made.

### CODE REVIEW

**Comment by satyam8932** [comment]
Your changes are failed to deploy because the code has errors.
Also please make sure that you add comments and use ESlint to properly lint you code formattings.

image

**Comment by satyam8932** [comment]
Still having the same deployment error

image

**Comment by Anandha-Vihari** [comment]
@satyam8932 can you assign me this issue ,i will do it..

**Comment by unknown91tech** [comment]
@satyam8932 I will resolve it in sometime

**Comment by satyam8932** [comment]
Due to no response and changes we are closing this PR.
Thanks

**Pull request closed without merging**
